---
title: "Mapa para relaciones Fundación Universidad Sociedad"
---

Este mapa se ha elaborado uniendo los datos proporcionados por el Consejo social. Se incluyen los datos de facturación y número de empleados obtenidos de SABI. No se han incluído entidades para las que, de momento, no tenemos estos datos. Los tipos de relación son club CEO u otras relaciones.

La agrupación en el eje horizontal se corresponde con una clasificación por sectores realizada ad-hoc. El tamaño del círculo se corresponde con el número de contactos. El eje vertical es el importe.


En este caso, se dispone ya del código <a href="https://www.cnae.com.es/lista-actividades.php" target="_blank">CNAE</a> en los datos. Con este código, se ha realizado una agrupación por sectores, realizada ad-hoc:

- Sector primario y extracción: Grupos CNAE A y B: 0_CNAE
- Sector Industria-Alimentación: Grupos CNAE C_10 y 11: 1_CNAE
- Sector Industria_Motor. Grupo CNAE 29: 2_CNAE
- Otra Industria y construcción. Grupos CNAE Resto Grupo C + GrupoF: 3_CNAE
- Suministros y Energía: Grupos CNAE D y E: 4_CNAE
- Comercio, Transporte, Hostelería: Grupos CNAE G, H, I: 5_CNAE
- Servicios: Información, Artístico, Informática, Consultoría, Financieros: Grupos CNAE J, K, L, M, N, R: 6_CNAE
- Admon, Pública, Educación, Asociaciones, Extraterrit: Grupos CNAE O ,P, Q, S, U: 7_CNAE

Con estos datos, se ha realizado un gráfico de dispersión con tres indicadores:

- Eje horizontal: es el sector con esta recodificación
- Eje vertical: son los ingresos en miles de euros de la entidad
- Eje z: El tamaño del círculo se corresponde con el número de contactos

```{r cnae, message=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
# compute new cnae (cs$CNAE, fus$CNAE, otri$CNAE)

cnae2009 <- read_csv("data/cnae2009.csv", 
                    col_types = cols(CODINTEGR = col_skip(), 
                     COD_CNAE2009 = col_character(), X4 = col_skip(), 
                     X5 = col_skip()))

#newcodes
# cuatro cifras

cnae4d<- cnae2009[which(nchar(cnae2009$COD_CNAE2009)==4),]

cnae4d$grupocnae <- 
      ifelse (cnae4d$COD_CNAE2009 < 1000,
            paste("0",cnae4d$COD_CNAE2009, sep=""),
      (ifelse((cnae4d$COD_CNAE2009 >= 1000) & (cnae4d$COD_CNAE2009 < 1200), 
            paste("1",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 1200) & (cnae4d$COD_CNAE2009 < 2900), 
            paste("3",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 2900) & (cnae4d$COD_CNAE2009 < 3000), 
            paste("2",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 3000) & (cnae4d$COD_CNAE2009 < 3500), 
            paste("3",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 4110) & (cnae4d$COD_CNAE2009 < 4400), 
            paste("3",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 3500) & (cnae4d$COD_CNAE2009 < 4000), 
            paste("4",cnae4d$COD_CNAE2009, sep=""), 
      ifelse((cnae4d$COD_CNAE2009 >= 4500) & (cnae4d$COD_CNAE2009 <= 5630), 
            paste("5",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 5800) & (cnae4d$COD_CNAE2009 <= 8299), 
            paste("6",cnae4d$COD_CNAE2009, sep=""),       
      ifelse((cnae4d$COD_CNAE2009 >= 9000) & (cnae4d$COD_CNAE2009 < 9330), 
            paste("6",cnae4d$COD_CNAE2009, sep=""), 
      ifelse((cnae4d$COD_CNAE2009 >= 8400) & (cnae4d$COD_CNAE2009 <= 8899), 
            paste("7",cnae4d$COD_CNAE2009, sep=""),       
      ifelse((cnae4d$COD_CNAE2009 >=9400), 
            paste("7",cnae4d$COD_CNAE2009, sep=""),       0
                    )))))))))))))

cnae4d$nombregrupo <- 
      ifelse (cnae4d$COD_CNAE2009 < 1000,
            paste("Sector primario y extracción"),
      ifelse((cnae4d$COD_CNAE2009 >= 1000) & (cnae4d$COD_CNAE2009 < 1200), 
            paste("Sector Industria-Alimentación"),
      ifelse((cnae4d$COD_CNAE2009 >= 1200) & (cnae4d$COD_CNAE2009 < 2900), 
            paste("Otra Industria y construcción"),
      ifelse((cnae4d$COD_CNAE2009 >= 2900) & (cnae4d$COD_CNAE2009 < 3000), 
            paste("Sector Industria_Motor"),
      ifelse((cnae4d$COD_CNAE2009 >= 3000) & (cnae4d$COD_CNAE2009 < 3500), 
            paste("Otra Industria y construcción"),
      ifelse((cnae4d$COD_CNAE2009 >= 4110) & (cnae4d$COD_CNAE2009 <= 4400), 
            paste("Otra Industria y construcción"),
      ifelse((cnae4d$COD_CNAE2009 >= 3500) & (cnae4d$COD_CNAE2009 <= 4000), 
            paste("Suministros y Energía"), 
      ifelse((cnae4d$COD_CNAE2009 >= 4500) & (cnae4d$COD_CNAE2009 <= 5630), 
            paste("Comercio, Transporte, Hostelería"),
      ifelse((cnae4d$COD_CNAE2009 >= 5800) & (cnae4d$COD_CNAE2009 <= 8299), 
            paste("Servicios: Información, Artístico, Informática, Consultoría, Financieros"),       
      ifelse((cnae4d$COD_CNAE2009 >= 9000) & (cnae4d$COD_CNAE2009 < 9330), 
            paste("Servicios: Información, Artístico, Informática, Consultoría, Financieros"), 
      ifelse((cnae4d$COD_CNAE2009 >= 8400) & (cnae4d$COD_CNAE2009 <= 8899), 
            paste("Admon. Pública, Educación, Asociaciones, Extraterrit"),       
      ifelse((cnae4d$COD_CNAE2009 >=9400), 
            paste("Admon. Pública, Educación, Asociaciones, Extraterrit"), 0
            ))))))))))))
rm(cnae2009)

# Mapa Cs
cs <- read_csv("data/ConsejoSocial_datosoriginales.csv", 
               locale = locale(asciify = TRUE), na = "empty")
# Hay algunos códigos cnae de 3 cifras incorrectos?

cnae3<- cs[which(nchar(cs$CNAE)<4),] # Localiza códigos de 3 cifras
cs[which(cs$CNAE=="812"),4]<-"8121"
rm(cnae3)
names(cs)<- c("razon", "nombre", "cif", "cnae", "ntrabaj", 
                        "totaling", "ingUPNA", "tipo", "tipo_10", "contacto", "aclaraciones")
l<-length(table(cs$cif)) #Comprobamos que cada fila es una empresa: no lo es
# hay bastantes perdidos: seleccionamos filas completas
cs_completos<- cs[complete.cases(cs), ]

l2<-length(table(cs_completos$cif)) #Comprobamos que cada fila es una empresa: sí lo es

# Completa los códigos
for (i in 1:length(cs_completos$cif)) {
      cs_completos[i, 12]<- cnae4d[grep(as.numeric(cs_completos[i,4]),cnae4d$grupocnae),3]
}


for (i in 1:length(cs_completos$cif)) {
      cs_completos[i, 13]<- cnae4d[grep(as.numeric(cs_completos[i,4]),cnae4d$grupocnae),4]
}

cs_completos$grupocnae <- as.numeric(cs_completos$grupocnae)

cs_completos$ingresos <- cs_completos$totaling/1000


# Variable X: grupocnae
# Variable Y: totaling
# https://plot.ly/r/getting-started/

library(devtools)
# devtools::install_github("ropensci/plotly")
library(plotly)
library("ggsci")
Sys.setenv("plotly_username"="mcortinas")
Sys.setenv("plotly_api_key"="yJb8VBxhRqDRAOesNWRT")

p <- ggplot(cs_completos, aes(x = grupocnae, y = ingresos)) +
      geom_point(aes(size = ntrabaj, color=tipo, alpha=3/4, 
                     text = paste("Nombre:", cs_completos$nombre))) +
      labs( title="Mapa de Relaciones Consejo Social" , subtitle = "(Solo datos completos)") +
      scale_y_continuous(name="Ingresos (miles de euros)")+
      scale_x_continuous(name="Sector", limits=c(0,80000), breaks=c(500,12000,22000,32000, 43000,54000,66000,78000),
                         labels=c("Sector primario y extracción", "Sector Industria-Alimentación", "Sector Industria_Motor",
                                  "Otra Industria y construcción", "Suministros y Energía", "Comercio, Transporte, Hostelería",
                                  "Servicios: Banca, Informática, Consultoría...",
                                  "Admon. Pública, Educación..."))+
      scale_color_lancet()+
      theme_bw()

gg <- ggplotly(p)
l <- list(
      font = list(
            family = "sans-serif",
            size = 16,
            color = "#000"),
      x = 0.05, 
      y = 0.95, 
      orientation = 'h',
      bordercolor = "#E2E2E2",
      borderwidth = 2)

l2 <- list(source = "http://www.unavarra.es/css/bitmaps/upna30-iberus.png?raw=true",
           xref = "x",
           yref = "y",
           x = 0.9,
           y = 3.1,
           sizex = 2,
           sizey = 2,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below"
      )
layout(gg, legend = l, images = l2)
```

Se puede hacer zoom sobre el mapa seleccionando cualquier cuadrante. "Reset zoom" devuelve el mapa a su tamaño original. También se puede seleccionar los tipos de relación (prácticas curriculares, extracurriculares o procesos de selección) pulsando sobre la leyenda del mapa.

Se incluyen otros datos como el nombre y el tipo de relación. 



<a href="maps/mapacs.html" target="_blank">Acceder en pantalla completa al mapa</a>
