---
title: "Mapa para relaciones Fundación Universidad Sociedad"
---

Este mapa se ha elaborado uniendo los datos proporcionados por la FUS. Los tipos de relación son prácticas curriculares, extracurriculares o procesos de selección. Se ha utilizado el nombre de la empresa, el NIF, el tipo de relación (acuerdo marco, servicios, asesoría, formación o I+D) y los ingresos. Es necesario tener en cuenta que los datos de facturación no son necesariamente abonados por las entidades, ya que depende del tipo de convenio.

En este caso, se dispone ya del código <a href="https://www.cnae.com.es/lista-actividades.php" target="_blank">CNAE</a> en los datos. Con este código, se ha realizado una agrupación por sectores, realizada ad-hoc:

- Sector primario y extracción: Grupos CNAE A y B: 0_CNAE
- Sector Industria-Alimentación: Grupos CNAE C_10 y 11: 1_CNAE
- Sector Industria_Motor. Grupo CNAE 29: 2_CNAE
- Otra Industria y construcción. Grupos CNAE Resto Grupo C + GrupoF: 3_CNAE
- Suministros y Energía: Grupos CNAE D y E: 4_CNAE
- Comercio, Transporte, Hostelería: Grupos CNAE G, H, I: 5_CNAE
- Servicios: Información, Artístico, Informática, Consultoría, Financieros: Grupos CNAE J, K, L, M, N, R: 6_CNAE
- Admon, Pública, Educación, Asociaciones, Extraterrit: Grupos CNAE O ,P, Q, S, U: 7_CNAE

Con estos datos, se ha realizado un gráfico de dispersión con tres indicadores:

- Eje horizontal: es el sector con esta recodificación
- Eje vertical: son los ingresos que genera cada relación
- Eje z: El tamaño del círculo se corresponde con el número de contactos

```{r cnae, message=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
# compute new cnae (cs$CNAE, fus$CNAE, otri$CNAE)

cnae2009 <- read_csv("data/cnae2009.csv", 
                    col_types = cols(CODINTEGR = col_skip(), 
                     COD_CNAE2009 = col_character(), X4 = col_skip(), 
                     X5 = col_skip()))

#newcodes
# cuatro cifras

cnae4d<- cnae2009[which(nchar(cnae2009$COD_CNAE2009)==4),]

cnae4d$grupocnae <- 
      ifelse (cnae4d$COD_CNAE2009 < 1000,
            paste("0",cnae4d$COD_CNAE2009, sep=""),
      (ifelse((cnae4d$COD_CNAE2009 >= 1000) & (cnae4d$COD_CNAE2009 < 1200), 
            paste("1",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 1200) & (cnae4d$COD_CNAE2009 < 2900), 
            paste("3",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 2900) & (cnae4d$COD_CNAE2009 < 3000), 
            paste("2",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 3000) & (cnae4d$COD_CNAE2009 < 3500), 
            paste("3",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 4110) & (cnae4d$COD_CNAE2009 < 4400), 
            paste("3",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 3500) & (cnae4d$COD_CNAE2009 < 4000), 
            paste("4",cnae4d$COD_CNAE2009, sep=""), 
      ifelse((cnae4d$COD_CNAE2009 >= 4500) & (cnae4d$COD_CNAE2009 <= 5630), 
            paste("5",cnae4d$COD_CNAE2009, sep=""),
      ifelse((cnae4d$COD_CNAE2009 >= 5800) & (cnae4d$COD_CNAE2009 <= 8299), 
            paste("6",cnae4d$COD_CNAE2009, sep=""),       
      ifelse((cnae4d$COD_CNAE2009 >= 9000) & (cnae4d$COD_CNAE2009 < 9330), 
            paste("6",cnae4d$COD_CNAE2009, sep=""), 
      ifelse((cnae4d$COD_CNAE2009 >= 8400) & (cnae4d$COD_CNAE2009 <= 8899), 
            paste("7",cnae4d$COD_CNAE2009, sep=""),       
      ifelse((cnae4d$COD_CNAE2009 >=9400), 
            paste("7",cnae4d$COD_CNAE2009, sep=""),       0
                    )))))))))))))

cnae4d$nombregrupo <- 
      ifelse (cnae4d$COD_CNAE2009 < 1000,
            paste("Sector primario y extracción"),
      ifelse((cnae4d$COD_CNAE2009 >= 1000) & (cnae4d$COD_CNAE2009 < 1200), 
            paste("Sector Industria-Alimentación"),
      ifelse((cnae4d$COD_CNAE2009 >= 1200) & (cnae4d$COD_CNAE2009 < 2900), 
            paste("Otra Industria y construcción"),
      ifelse((cnae4d$COD_CNAE2009 >= 2900) & (cnae4d$COD_CNAE2009 < 3000), 
            paste("Sector Industria_Motor"),
      ifelse((cnae4d$COD_CNAE2009 >= 3000) & (cnae4d$COD_CNAE2009 < 3500), 
            paste("Otra Industria y construcción"),
      ifelse((cnae4d$COD_CNAE2009 >= 4110) & (cnae4d$COD_CNAE2009 <= 4400), 
            paste("Otra Industria y construcción"),
      ifelse((cnae4d$COD_CNAE2009 >= 3500) & (cnae4d$COD_CNAE2009 <= 4000), 
            paste("Suministros y Energía"), 
      ifelse((cnae4d$COD_CNAE2009 >= 4500) & (cnae4d$COD_CNAE2009 <= 5630), 
            paste("Comercio, Transporte, Hostelería"),
      ifelse((cnae4d$COD_CNAE2009 >= 5800) & (cnae4d$COD_CNAE2009 <= 8299), 
            paste("Servicios: Información, Artístico, Informática, Consultoría, Financieros"),       
      ifelse((cnae4d$COD_CNAE2009 >= 9000) & (cnae4d$COD_CNAE2009 < 9330), 
            paste("Servicios: Información, Artístico, Informática, Consultoría, Financieros"), 
      ifelse((cnae4d$COD_CNAE2009 >= 8400) & (cnae4d$COD_CNAE2009 <= 8899), 
            paste("Admon. Pública, Educación, Asociaciones, Extraterrit"),       
      ifelse((cnae4d$COD_CNAE2009 >=9400), 
            paste("Admon. Pública, Educación, Asociaciones, Extraterrit"), 0
            ))))))))))))
rm(cnae2009)

# MAPA FUS
fus <- read_csv("data/Fus_Listado empresas.csv", na="",
      locale = locale(asciify = TRUE))

names(fus)<-gsub(" ", "", names(fus)) # Quitar espacios en blanco
# Hay algunos códigos cnae de 3 cifras incorrectos
# Los corregimos:
cnae3<- fus[which(nchar(fus$CNAE_1)==3),] # Localiza códigos de 3 cifras
fus[which(fus$CNAE_1=="113"),5]<-"0113"
fus[which(fus$CNAE_1=="161"),5]<-"0161"
fus[which(fus$CNAE_1=="163"),5]<-"6201"
fus[which(fus$CNAE_1=="729"),5]<-"0729"
rm(cnae3)

l<-length(table(fus$Name)) #Comprobamos que cada fila es una empresa

# Completa los códigos
for (i in 1:length(fus$No_)) {
      fus[i, 11]<- cnae4d[grep(as.numeric(fus[i,5]),cnae4d$grupocnae),3]
      }

# Añade el nombre
for (i in 1:length(fus$No_)) {
      fus[i, 12]<- cnae4d[grep(as.numeric(fus[i,5]),cnae4d$grupocnae),4]}
fus$grupocnae <- as.numeric(fus$grupocnae)

# Para hacer el gráfico
# "poner en formato largo"
library(tidyr)
fus$No_ <- factor(fus$No_)
fus_long <- gather(fus, tipo, convenios, Practicascurriculares2016:Selecciones2016Empleootrabajo, factor_key=TRUE)
fus_long$tipo<- factor(fus_long$tipo, labels=c("Pract. Curriculares", "Pract. Extracurriculares","Proceso Selección" ))

# Variable X: grupocnae
# Variable Y: convenios
# facets: tipo
# size: Ingresos2016
# https://plot.ly/r/getting-started/

library(devtools)
# devtools::install_github("ropensci/plotly")
library(plotly)
library("ggsci")
Sys.setenv("plotly_username"="mcortinas")
Sys.setenv("plotly_api_key"="yJb8VBxhRqDRAOesNWRT")
c<-Sys.setlocale("LC_CTYPE","spanish")
p <- ggplot(fus_long, aes(x = grupocnae, y = convenios)) +
      geom_point(aes(size = Ingresos2016, color=tipo, marker=list(alpha=3/4), text = paste("Nombre:", fus_long$ALIAS))) +
      labs( title="Mapa de Relaciones FUS" , subtitle = NULL) +
      scale_y_continuous(name="Número de Convenios", limits=c(0,70), breaks=c(5,10,15,20, 40,70))+
      scale_x_continuous(name="Sector", limits=c(0,80000), breaks=c(500,12000,22000,32000, 43000,54000,66000,78000),
                         labels=c("Sector primario y extracción", "Sector Industria-Alimentación", "Sector Industria_Motor",
                                  "Otra Industria y construcción", "Suministros y Energía", "Comercio, Transporte, Hostelería",
                                  "Servicios: Banca, Informática, Consultoría...",
                                  "Admon. Pública, Educación..."))+
      scale_color_startrek()+
      theme_bw()

gg <- ggplotly(p)
l <- list(
      font = list(
            family = "sans-serif",
            size = 16,
            color = "#000"),
      x = 0.05, 
      y = 0.95, 
      orientation = 'h',
      bordercolor = "#E2E2E2",
      borderwidth = 2)

l2 <- list(source = "https://www.unavarra.es/digitalAssets/103/103080_100000upna-logo-2018-con-leyenda.png",
           xref = "x",
           yref = "y",
           x = 0.9,
           y = 3.1,
           sizex = 2,
           sizey = 2,
           sizing = "stretch",
           opacity = 0.4,
           layer = "below"
)

      
layout(gg, legend = l, images = l2)

# Variable X: grupocnae
# Variable Y: ingresos
# facets: tipo
# size: ambito
# https://plot.ly/r/getting-started/
```

Se puede hacer zoom sobre el mapa seleccionando cualquier cuadrante. "Reset zoom" devuelve el mapa a su tamaño original. También se puede seleccionar los tipos de relación (prácticas curriculares, extracurriculares o procesos de selección) pulsando sobre la leyenda del mapa.

Se incluyen otros datos como el nombre y el tipo de relación. 



<a href="maps/mapafus.html" target="_blank">Acceder en pantalla completa al mapa</a>
